- name: Configure LDAP servers
  hosts: ldap_servers
  become: true
  roles:
    - ldap_server
    - firewall

- name: Configure LDAP clients
  hosts: ldap_clients
  become: true
  roles:
    - ldap_client

