- name: Install LDAP client packages
  dnf:
    name:
      - openldap
      - openldap-clients
      - nss-pam-ldapd
    state: present

- name: Template /etc/openldap/ldap.conf
  template:
    src: ldap.conf.j2
    dest: /etc/openldap/ldap.conf
    mode: '0644'

- name: Template /etc/nslcd.conf
  template:
    src: nslcd.conf.j2
    dest: /etc/nslcd.conf
    mode: '0600'

- name: Template /etc/authselect/user-nsswitch.conf
  template:
    src: user-nsswitch.conf.j2
    dest: /etc/authselect/user-nsswitch.conf
    mode: '0644'

- name: Apply NSS configuration via authselect
  command: authselect apply-changes

- name: Enable and start nslcd
  systemd:
    name: nslcd
    enabled: true
    state: started

