- name: Enable required AppStream repo (if needed)
  command: >
    subscription-manager repos --enable=rhel-8-for-x86_64-appstream-rpms
  register: enable_repo
  failed_when: false
  changed_when: "'is already enabled' not in enable_repo.stdout"

- name: Reset existing 389-ds module streams
  command: dnf module reset 389-ds -y

- name: Enable 389-ds module stream
  command: dnf module enable 389-ds -y

- name: Clean DNF cache
  command: dnf clean all

- name: Rebuild DNF cache
  command: dnf makecache

- name: Install 389 Directory Server
  dnf:
    name: 389-ds-base
    state: present


- name: Install 389-ds-base
  dnf:
    name: 389-ds-base
    state: present

- name: Template base.ldif
  template:
    src: base.ldif.j2
    dest: /root/base.ldif
    mode: '0644'

- name: Template ou.ldif
  template:
    src: ou.ldif.j2
    dest: /root/ou.ldif
    mode: '0644'

- name: Template users.ldif
  template:
    src: users.ldif.j2
    dest: /root/users.ldif
    mode: '0644'

- name: Template group.ldif
  template:
    src: group.ldif.j2
    dest: /root/group.ldif
    mode: '0644'

- name: Template hosts.ldif
  template:
    src: hosts.ldif.j2
    dest: /root/hosts.ldif
    mode: '0644'

- name: Template anonymous-aci.ldif
  template:
    src: anonymous-aci.ldif.j2
    dest: /root/anonymous-aci.ldif
    mode: '0644'


- name: Run interactive setup (idempotent method)
  command: dscreate from-file /root/instance.inf
  args:
    creates: /etc/dirsrv/slapd-ldap

- name: Start and enable 389 Directory Server
  systemd:
    name: dirsrv@ldap
    enabled: true
    state: started

- name: Load base DIT
  command: >
    ldapadd -x -D "{{ ldap_bind_dn }}" -w "{{ ldap_bind_pw }}" -H "{{ ldap_uri }}" -f /root/base.ldif
  args:
    creates: /var/lib/dirsrv/slapd-ldap/DB_CONFIG

- name: Add organizational units
  command: ldapadd -x -D "{{ ldap_bind_dn }}" -w "{{ ldap_bind_pw }}" -H "{{ ldap_uri }}" -f /root/ou.ldif

- name: Add user accounts
  command: ldapadd -x -D "{{ ldap_bind_dn }}" -w "{{ ldap_bind_pw }}" -H "{{ ldap_uri }}" -f /root/users.ldif

- name: Add group
  command: ldapadd -x -D "{{ ldap_bind_dn }}" -w "{{ ldap_bind_pw }}" -H "{{ ldap_uri }}" -f /root/group.ldif

- name: Add host entries
  command: ldapadd -x -D "{{ ldap_bind_dn }}" -w "{{ ldap_bind_pw }}" -H "{{ ldap_uri }}" -f /root/hosts.ldif

- name: Enable anonymous read access to DIT
  command: ldapmodify -x -D "{{ ldap_bind_dn }}" -w "{{ ldap_bind_pw }}" -H "{{ ldap_uri }}" -f /root/anonymous-aci.ldif

