- name: Install LDAP client packages
  dnf:
    name:
      - openldap
      - openldap-clients
      - nss-pam-ldapd
    state: present

- name: Configure /etc/openldap/ldap.conf
  copy:
    dest: /etc/openldap/ldap.conf
    content: |
      BASE {{ ldap_suffix }}
      URI {{ ldap_uri }}

- name: Configure /etc/nslcd.conf
  copy:
    dest: /etc/nslcd.conf
    content: |
      uri {{ ldap_uri }}
      base {{ ldap_suffix }}
      base hosts ou=hosts,{{ ldap_suffix }}

- name: Start and enable nslcd
  systemd:
    name: nslcd
    enabled: true
    state: started

- name: Update /etc/nsswitch.conf
  lineinfile:
    path: /etc/nsswitch.conf
    regexp: '^hosts:'
    line: 'hosts: files dns ldap'

