---
- name: Check if Samba is installed
  command: rpm -q samba
  register: samba_installed
  failed_when: false
  changed_when: false

- name: Install Samba if not installed
  dnf:
    name:
      - samba
      - samba-client
      - samba-common
      - cifs-utils
    state: present
  when: samba_installed.rc != 0

- name: Ensure /srv/samba/public exists
  file:
    path: /srv/samba/public
    state: directory
    owner: nobody
    group: nobody
    mode: '0777'

- name: Create user1
  user:
    name: user1
    state: present

- name: Set password for user1
  expect:
    command: smbpasswd -a user1
    responses:
      (?i)New SMB password: "user1\n"
      (?i)Retype new SMB password: "user1\n"

- name: Create user2
  user:
    name: user2
    state: present

- name: Set password for user2
  expect:
    command: smbpasswd -a user2
    responses:
      (?i)New SMB password: "user2\n"
      (?i)Retype new SMB password: "user2\n"

- name: Ensure /srv/samba/private exists
  file:
    path: /srv/samba/private
    state: directory
    mode: '0770'
    owner: user1
    group: user1

- name: Set ACL for user2 on private share
  command: setfacl -m u:user2:rx /srv/samba/private

- name: Deploy smb.conf
  template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart Samba

- name: Enable and start smb service
  systemd:
    name: smb
    enabled: true
    state: started


