- name: Create "{{ new_user }}" user with sudo (wheel) access
  user:
    name: "{{ new_user }}"
    password: "{{ new_user_pass  | password_hash('sha512') }}"
    groups: wheel
    append: yes
    update_password: on_create


