- name: Ensure output file is clean
  copy:
    content: ""
    dest: /root/verification.log
    force: true
    owner: root
    mode: '0644'

- name: Copy verification helper script
  template:
    src: verify_helper.sh.j2
    dest: /usr/local/bin/verify_helper.sh
    mode: '0755'

- name: Run full verification suite
  shell: /usr/local/bin/verify_helper.sh >> /root/verification.log 2>&1
  args:
    executable: /bin/bash

