- name: Install NFS packages
  dnf:
    name: "{{ nfs_packages }}"
    state: present

- name: Enable and start nfs-server
  systemd:
    name: nfs-server
    enabled: true
    state: started

- name: Ensure NFS share directory exists
  file:
    path: "{{ nfs_path }}"
    state: directory
    owner: root
    group: root
    mode: '0777'

- name: Create readme.nfs with student name
  copy:
    content: "Created by Hmoad Hajali\n"
    dest: "{{ nfs_path }}/readme.nfs"
    mode: '0644'

- name: Configure exports
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: '0644'
  notify: Export NFS Shares

